version: '3.8'

services:
  info-dashboard:
    image: cklx0719/info-dashboard:latest
    container_name: info-dashboard
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      # 挂载API配置文件
      - ./app/config/api.ts:/app/config/api.ts:ro
      # 挂载日志目录
      - ./logs:/var/log/nginx
    environment:
      # 时区设置
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - info-dashboard-network

networks:
  info-dashboard-network:
    driver: bridge

# 可选：如果需要数据持久化
volumes:
  nginx-logs:
    driver: local